-- ==========================================
-- SCRIPT PARA CREAR TABLA DE CÓDIGOS DE INVITACIÓN
-- ==========================================
-- Ejecutar este script en Supabase SQL Editor
-- para habilitar el control de códigos de invitación de un solo uso

-- 8. TABLA DE CÓDIGOS DE INVITACIÓN
-- Controla los códigos para registrar nuevos negocios (un solo uso)
create table if not exists public.invitation_codes (
  id bigint generated by default as identity primary key,
  code text not null unique, -- Código de invitación único
  used boolean default false, -- Si ya fue usado
  used_by uuid references auth.users, -- Usuario que usó el código (si fue usado)
  used_at timestamp with time zone, -- Fecha/hora de uso
  created_by text, -- Quién creó el código (administrador)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  expires_at timestamp with time zone, -- Fecha de expiración (opcional)
  notes text -- Notas adicionales
);

-- Habilitar RLS
alter table public.invitation_codes enable row level security;

-- Política: Cualquiera puede leer códigos para validación (pero solo campos necesarios)
-- Para validación, solo necesitan ver si existe y si está usado
create policy "Anyone can read invitation codes for validation" on public.invitation_codes
  for select using (true);

-- Política: Solo autenticados pueden actualizar (marcar como usado)
-- Esto se hace automáticamente cuando alguien se registra
create policy "Authenticated users can mark codes as used" on public.invitation_codes
  for update using (auth.role() = 'authenticated');

-- Política: Permitir inserción pública (para que los admins puedan crear códigos)
-- Nota: En producción, considera restringir esto a un servicio admin
create policy "Anyone can create invitation codes" on public.invitation_codes
  for insert with check (true);

-- ==========================================
-- EJEMPLO: Crear algunos códigos de invitación iniciales
-- ==========================================
-- Puedes ejecutar estos INSERT para crear códigos de prueba
-- O crearlos desde el dashboard de Supabase

insert into public.invitation_codes (code, created_by, notes) values 
  ('ADMIN2024', 'Administración', 'Código de invitación principal'),
  ('POS-REG-2024', 'Administración', 'Código para registro de negocios'),
  ('BIZ-PRO-2024', 'Administración', 'Código profesional de registro')
on conflict (code) do nothing; -- No insertar si ya existe

-- ==========================================
-- CONSULTAS ÚTILES
-- ==========================================

-- Ver todos los códigos y su estado
-- SELECT id, code, used, used_by, used_at, created_at, expires_at, notes 
-- FROM public.invitation_codes 
-- ORDER BY created_at DESC;

-- Ver solo códigos no usados
-- SELECT code, created_at, expires_at, notes 
-- FROM public.invitation_codes 
-- WHERE used = false 
-- ORDER BY created_at DESC;

-- Ver códigos usados con información del usuario
-- SELECT ic.code, ic.used_at, p.store_name, p.full_name 
-- FROM public.invitation_codes ic
-- LEFT JOIN public.profiles p ON ic.used_by = p.id
-- WHERE ic.used = true
-- ORDER BY ic.used_at DESC;
