-- ==========================================
-- ESQUEMA DE BASE DE DATOS PARA SISTEMA VENTAS SAAS
-- ==========================================

-- 1. TABLA DE PERFILES (Tiendas)
-- Se vincula automáticamente con la tabla auth.users de Supabase
create table public.profiles (
  id uuid references auth.users not null primary key,
  store_name text,
  full_name text,
  role text default 'admin', -- 'admin' | 'cajero'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS (Seguridad)
alter table public.profiles enable row level security;

-- Política: Los usuarios pueden ver y editar su propio perfil
create policy "Users can view own profile" on public.profiles
  for select using (auth.uid() = id);

create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id);

create policy "Users can insert own profile" on public.profiles
  for insert with check (auth.uid() = id);

-- 2. TABLA DE PRODUCTOS
create table public.products (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(), -- Dueño del producto
  name text not null,
  price numeric not null,
  stock integer not null default 0,
  barcode text,
  image_url text, -- URL de la imagen en Storage
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS
alter table public.products enable row level security;

-- Política CRÍTICA: Aislamiento total (SaaS)
-- Un usuario solo puede ver, crear, editar y borrar productos donde user_id sea SU id.
create policy "Users can CRUD own products" on public.products
  for all using (auth.uid() = user_id);

-- 3. TABLA DE VENTAS
create table public.sales (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  total numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS
alter table public.sales enable row level security;

-- Política de aislamiento
create policy "Users can CRUD own sales" on public.sales
  for all using (auth.uid() = user_id);

-- 4. TABLA DE DETALLE DE VENTAS (Items)
-- Para tener un registro relacional mejor que un JSON gigante
create table public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint references public.sales on delete cascade not null,
  user_id uuid references auth.users not null default auth.uid(), -- Redundancia útil para RLS
  product_name text not null, -- Guardamos nombre por si luego se borra el producto
  quantity integer not null,
  price numeric not null,
  total numeric not null
);

-- Habilitar RLS
alter table public.sale_items enable row level security;

-- Política de aislamiento
create policy "Users can CRUD own sale items" on public.sale_items
  for all using (auth.uid() = user_id);

-- 5. TABLA DE EMPLEADOS (Staff)
-- Empleados de cada tienda con PIN para acceso rápido
create table public.staff (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(), -- Dueño de la tienda
  name text not null,
  role text default 'cajero', -- 'admin' | 'cajero' | 'gerente'
  pin text not null, -- PIN hasheado o simple (4-6 dígitos)
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS
alter table public.staff enable row level security;

-- Política: Solo el dueño puede gestionar su staff
create policy "Users can CRUD own staff" on public.staff
  for all using (auth.uid() = user_id);

-- 7. TABLA DE CORTES DE CAJA
-- Registra cierres de turno y cortes de caja
create table public.cash_cuts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(), -- Dueño de la tienda
  staff_name text not null, -- Nombre del empleado que hizo el corte
  staff_role text, -- Rol del empleado
  cut_type text not null, -- 'turno' | 'dia' | 'parcial'
  start_time timestamp with time zone not null, -- Inicio del período
  end_time timestamp with time zone not null default now(), -- Fin del período
  sales_count integer not null default 0, -- Cantidad de ventas
  sales_total numeric not null default 0, -- Total de ventas en efectivo
  expected_cash numeric not null default 0, -- Efectivo esperado
  actual_cash numeric, -- Efectivo contado (puede ser null si no se contó)
  difference numeric, -- Diferencia (actual - expected)
  notes text, -- Observaciones
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS
alter table public.cash_cuts enable row level security;

-- Política: Solo el dueño puede ver y crear cortes de su tienda
create policy "Users can CRUD own cash_cuts" on public.cash_cuts
  for all using (auth.uid() = user_id);

-- 8. STORAGE (BUCKETS)
-- Nota: Esto normalmente se hace desde la UI, pero si usas SQL:
insert into storage.buckets (id, name, public) values ('products', 'products', true);

-- Política de Storage: Cualquiera puede ver, solo el dueño puede subir/borrar
create policy "Public Access" on storage.objects for select using ( bucket_id = 'products' );
create policy "Auth Upload" on storage.objects for insert with check ( bucket_id = 'products' and auth.role() = 'authenticated' );
